### ISSUE TITLE
link breaks when inserting method as parameter

### ISSUE THREAD

**Issue by hebertlima** [nhedger/vscode-inertia#16]
when using the `compact()` function the link is broken

```php
Inertia::render('foo/bar/page', compact('data'));
```

the function `compact()` is interpreted as being part of the link, not stopping at the comma

<img width="575" alt="image" src="https://user-images.githubusercontent.com/34013325/213831720-33ea62d0-09ba-4a2b-a6ca-50976da4f79f.png">

**Comment by nhedger** [comment]
Thanks for reporting. I'll have a look and fix it ASAP.

**Comment by nhedger** [comment]
This issue have been fixed and released @hebertlima.
