### ISSUE TITLE
Component link not working with inertia()

### ISSUE THREAD

**Issue by AliceKLWilliams** [nhedger/vscode-inertia#19]
Hi, thanks for making this extension, it's super useful!

The component links don't work when using `inertia()`.

It works when there is no content before the function call (including no indentation):

![image](https://user-images.githubusercontent.com/25745335/216276314-b6ccca9d-3111-4347-937a-5ed48652d8f8.png)

But once you add any content before the function call (including just indentation), it no longer links:

![image](https://user-images.githubusercontent.com/25745335/216276504-e9da0dbe-280b-4146-a1ce-7b81d35ecbde.png)

**Comment by nhedger** [comment]
Hey @AliceKLWilliams, thank you for reporting this issue.

The latest version fixes this issue and it should be available on the marketplace is a few minutes.

Please let me know if you find any other issues.
